Fix UninitializedRecheckIgnoreException
de.retest.elementcollection.UninitializedRecheckIgnoreException: recheck ignore must be loaded before being used.
	at de.retest.elementcollection.RecheckIgnore.getInstance(RecheckIgnore.java:50)
	at de.retest.report.ReplayResult.<init>(ReplayResult.java:62)
	at de.retest.report.ReplayResult.fromApi(ReplayResult.java:45)
	at de.retest.recheck.persistence.RecheckReplayResultUtil.persist(RecheckReplayResultUtil.java:25)
	at de.retest.recheck.persistence.RecheckReplayResultUtilTest.persist_should_create_report_if_no_errors(RecheckReplayResultUtilTest.java:33)