Do not log irrelevant exceptions, like a missing optional file
ERROR [pool-3-thread-1] [de.retest.recheck.ignore.JSFilterImpl] - Error opening JS file from '/Users/roessler/.retest/recheck.ignore.js':
 java.nio.file.NoSuchFileException: /Users/roessler/.retest/recheck.ignore.js
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.newByteChannel(Files.java:407)
	at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
	at java.nio.file.Files.newInputStream(Files.java:152)
	at java.nio.file.Files.newBufferedReader(Files.java:2784)
	at de.retest.recheck.ignore.JSFilterImpl.readScriptFile(JSFilterImpl.java:44)
	at de.retest.recheck.ignore.JSFilterImpl.<init>(JSFilterImpl.java:35)
	at de.retest.recheck.review.workers.LoadFilterWorker.lambda$load$1(LoadFilterWorker.java:47)
	at java.util.Optional.ifPresent(Optional.java:159)