Avoid java.lang.NoClassDefFoundError
java.lang.NoClassDefFoundError: javax/mail/Message
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethods(Class.java:1975)
	at de.retest.recheck.TestCaseFinder.tryToFindMethodForStackTraceElement(TestCaseFinder.java:87)
	at de.retest.recheck.TestCaseFinder.isTestCase(TestCaseFinder.java:61)
	at de.retest.recheck.TestCaseFinder.findTestCaseMethodInStack(TestCaseFinder.java:51)
	at de.retest.util.ApprovalsUtil$JUnitStackSelector.selectElement(ApprovalsUtil.java:76)
	at com.spun.util.tests.TestUtils.getCurrentFileForMethod(TestUtils.java:265)
	at com.spun.util.tests.TestUtils.getCurrentFileForMethod(TestUtils.java:258)
	at de.retest.util.ApprovalsUtil$MavenConformJUnitStackTraceNamer.<init>(ApprovalsUtil.java:57)
	at de.retest.util.ApprovalsUtil.verify(ApprovalsUtil.java:35)
	at de.retest.util.ApprovalsUtil.verifyXml(ApprovalsUtil.java:30)
	at de.retest.persistence.migration.RemoveElementTransformerTest.simple_xml_element_should_be_removed(RemoveElementTransformerTest.java:26)
Caused by: java.lang.ClassNotFoundException: javax.mail.Message
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 13 more